version: '3.8'

services:
  backend:
    build: .
    container_name: math-backend
    command: ./entrypoint.sh
    volumes:
      - ./src/app:/app/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mathchallenger
    depends_on:
      - db
    ports:
      - "8001:8000"

  db:
    image: postgres:16
    container_name: math-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mathchallenger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: math-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
